Feat: component conference card
Fork-It-Community/forkit.community pull request #103
Opened 2024-09-03 15:28 UTC by build-ratchanon

## What do I do?
update, 3 Sep.
- add badge, location badge, language badge and favorite button from the existing one.
- add conference card [ In-progress for now. ]

## Related issue
- #78

2024-09-17 17:22 UTC, houssembaltii requested changes

2024-09-17 17:22 UTC, houssembaltii commented on src/components/conference-card.tsx
> +                            key={speaker.id || index}
i dont think we will ever see a conference without speakers , so 
```suggestion
                            key={speaker.id}
```

2024-09-17 17:22 UTC, houssembaltii commented on src/components/conference-card.tsx
> +                    language={talk?.data?.language as "french" | "english"}
* You declared data of type `Talk` in `TalkStateProps`, so `talk.data` is already of type Talk.
* In `src/content/talks`, the language attribute is already an enum of English and French, so it's unnecessary to redefine it as "french" | "english".

2024-09-17 17:22 UTC, houssembaltii commented on src/components/conference-card.tsx
> +  }
I think making  `BreakCard` async and using getEntry directly instead of doing useState and useEffect is better , maybe @yoannfleurydev  can confirm me or correct me

2024-09-18 10:26 UTC, build-ratchanon commented on src/components/conference-card.tsx
> +
Thanks for your feedback @houssembaltii . about the SpeakerStateProps. i need to get the spaker slug to find a speaker name inside the talk.

2024-09-18 10:29 UTC, build-ratchanon commented on src/components/conference-card.tsx
> +
But for Talk, I have fixed it as you suggested.

2024-09-24 07:55 UTC, DecampsRenan requested changes

2024-09-24 07:55 UTC, DecampsRenan commented on src/components/conference-card.tsx
> +        <time dateTime={props.startTime?.toISOString()}>
```suggestion
        <time dateTime={props.startTime.toISOString()}>
```

The `?` is not needed here, you already made sure that startTime is defined l.31 ;)

2024-09-24 07:55 UTC, DecampsRenan commented on src/components/conference-card.tsx
> +      if (props?.activity?.slug) {
`?` not needed too, you checked that it is defined l.65 :)

2024-09-24 07:55 UTC, DecampsRenan commented on src/components/conference-card.tsx
> +        const fetchedTalk = await getEntry("talks", props?.activity?.slug);
same

2024-09-24 07:55 UTC, DecampsRenan commented on src/components/conference-card.tsx
> +            fetchedTalk?.data?.speakers.map(async (speaker: string) => {
same, check l.75

2024-09-24 07:55 UTC, DecampsRenan commented on src/components/conference-card.tsx
> +          props?.break?.sponsorSlug,
`?` not needed for the same reason ;) 

Basically, if the tsconfig.json file is strict, ts will warn you if you try to access a maybe undefined or null value ;)

2024-09-24 07:55 UTC, DecampsRenan commented on src/components/conference-card.tsx
> +          props?.break?.sponsorSlug,
so by default, you can omit `?` :) and you will be warned if it is needed

2024-09-24 07:59 UTC, yoannfleurydev commented on src/components/conference-card.tsx
> +  }
Completely agree

2024-10-02 12:00 UTC, closed without merging