Feat: component tag
Fork-It-Community/forkit.community pull request #113
Opened 2024-09-11 04:02 UTC by build-ratchanon

## What do i do?
- create component Tag

## Screenshot
![image](https://github.com/user-attachments/assets/63bb9d23-bab6-4990-929b-d17717d1f556)

2024-09-11 12:32 UTC, JeanneGrenet approved these changes

2024-09-17 14:24 UTC, houssembaltii approved these changes

2024-09-24 07:46 UTC, DecampsRenan requested changes

2024-09-24 07:46 UTC, DecampsRenan commented on src/components/ui/tag.tsx
> +export { Tag, tagVariants };
it's a good practice to add a new line at the end of the file (it's a unix good practice, and some cli tools rely on that to work properly ;) )

![CleanShot 2024-09-24 at 09 43 51@2x](https://github.com/user-attachments/assets/e019349e-4453-4c59-ab0b-e863e73615e1)

I see that prettier is setup; have you got prettier enabled on your editor ? it should add this empty line for you on each save

You can try to run `npm run pretty` to fix formating issues like this one ;)

Adding something like husky or lefthook should prevent this issue

2024-09-24 12:00 UTC, DecampsRenan commented on src/components/ui/tag.tsx
> +export { Tag, tagVariants };
Same as the other PR, I re-checked the project and it is using pnpm on the feat/v2 branch

So it should be `pnpm prettier . --write` or something like this (or just fix this file, as you wish :) )

2024-09-26 10:55 UTC, merged