feat: create faq component
Fork-It-Community/forkit.community pull request #114
Opened 2024-09-11 11:01 UTC by build-ratchanon

## What do i do?
- create FAQ component

## Screenshot
![image](https://github.com/user-attachments/assets/3728f0df-5a77-4d08-adf2-68e31a49e5c5)

## Related Card
#81

2024-09-11 12:27 UTC, JeanneGrenet approved these changes

2024-09-17 14:17 UTC, houssembaltii approved these changes

2024-09-24 07:53 UTC, DecampsRenan requested changes

2024-09-24 07:53 UTC, DecampsRenan commented on package.json
> +    "@radix-ui/react-accordion": "^1.2.0",
please fix the version to 1.2.0 ;) we do that to prevent issues where another dev install deps, and instead of 1.2.0 it will maybe install 1.2.3 and have an issue nobody can reproduce

It's a good practice to set versions without `^` or `~` ;)

2024-09-24 07:53 UTC, DecampsRenan commented on src/components/faq.tsx
> +}
try run `npm run pretty` to fix endOfLine issues :)

2024-09-24 11:59 UTC, DecampsRenan commented on src/components/faq.tsx
> +}
my bad, I re-check the project and it is using pnpm on the feat/v2 branch

So it should be `pnpm prettier . --write` or something like this (or just fix this file, as you wish :) )

2024-10-08 11:32 UTC, closed without merging