Feat : create layouts and SEO
Fork-It-Community/forkit.community pull request #117
Opened 2024-09-13 09:43 UTC by JeanneGrenet

## Description : 
Create a generic layout and a specific layout for events and subpages events using generic layout

2024-09-24 14:25 UTC, houssembaltii requested changes
* in the issue , we have rss feed that is missing here 
*  how to manage SEO for each page , i only see  `<slot name="seo"/>`  ,
* SEO :  open graph and twitter attributes are  missing 
* check prettier configuration , i think it's not formatting code on save .

2024-09-24 14:25 UTC, houssembaltii commented on astro.config.mjs
> +import sitemap from "@astrojs/sitemap";
can you run prettier command to format  this file

2024-09-24 14:25 UTC, houssembaltii commented on src/layouts/Layout.astro
> +    <meta name="description" content={description || title}/>
same for this file

2024-09-24 14:25 UTC, houssembaltii commented on src/layouts/Layout.astro
> +    <slot name="seo" />
can u add the pull request description , how are we gonna maange seo for each page using this slot .

2024-09-30 12:17 UTC, JeanneGrenet commented on src/layouts/Layout.astro
> +    <slot name="seo" />
Yes I added the astro-seo lib to manage it easily

2024-09-30 12:39 UTC, merged