prepare blog section
Fork-It-Community/forkit.community pull request #119
Opened 2024-09-18 08:51 UTC by houssembaltii

2024-09-18 16:22 UTC, JeanneGrenet requested changes

2024-09-18 16:22 UTC, JeanneGrenet commented on src/content/blogs/blogs.ts
> +    author: z.object({
I think we can add an optional picture for the author because we already have pictures for speakers and organizers

2024-09-19 11:51 UTC, yoannfleurydev requested changes

2024-09-19 11:51 UTC, yoannfleurydev commented on src/content/blogs/blogs.ts
> +    BlogImage: z
```suggestion
    featuredImage: z
```

2024-09-19 11:51 UTC, yoannfleurydev commented on src/content/blogs/blogs.ts
> +    author: z.object({
We will need to reference a `people` collection. We do not need to redefine people in every collection then

2024-09-19 11:51 UTC, yoannfleurydev commented on src/content/blogs/blogs.ts
> +    readingTime: z.number().optional(),
Can be computed, we don't want to bother providing this value.

2024-09-19 11:51 UTC, yoannfleurydev commented on src/content/blogs/blogs.ts
> +    isTopPost: z.boolean(),
Can be done in a config file, using blog post slug, so blog post don't hold this information

2024-10-05 12:24 UTC, yoannfleurydev approved these changes

2024-10-05 12:25 UTC, merged