prepare podcast section
Fork-It-Community/forkit.community pull request #122
Opened 2024-09-18 16:12 UTC by houssembaltii

2024-09-18 16:28 UTC, JeanneGrenet requested changes

2024-09-18 16:28 UTC, JeanneGrenet commented on src/content/podcasts/podcasts.ts
> +    guests: z.array(z.string()),
I think these props can be an object with name and optional picture

2024-10-05 12:34 UTC, yoannfleurydev requested changes

2024-10-05 12:34 UTC, yoannfleurydev commented on src/content/podcasts/podcasts.ts
> +    episodeNumber: z.number(),
Not sure about that one (will be in the episode title I think)

2024-10-05 12:34 UTC, yoannfleurydev commented on src/content/podcasts/podcasts.ts
> +    podcastUrls: z
```suggestion
    urls: z
```

2024-10-05 12:34 UTC, yoannfleurydev commented on src/content/podcasts/podcasts.ts
> +          url: z.string(),
```suggestion
          url: z.string().url(),
```

2024-10-05 12:34 UTC, yoannfleurydev commented on src/content/podcasts/podcasts.ts
> +          platform: z.string(),
```suggestion
          name: z.string(),
```

2024-10-05 12:34 UTC, yoannfleurydev commented on src/content/podcasts/podcasts.ts
> +      .optional(),
Can you explain and maybe add a comment to explain that one please?

2024-10-07 08:11 UTC, houssembaltii commented on src/content/podcasts/podcasts.ts
> +      .optional(),
I inspired notes field from [syntax fm ](https://syntax.fm/show/822/receipt-printer-with-javascript), where notes will be an array that contains topics and which minute it has been talked about for example : 
* 01:10 : What is Fork It ?
* 2:00 : ForkIt Organizers 
...

2024-12-24 12:29 UTC, closed without merging