feat : add bangkok meetup
Fork-It-Community/forkit.community pull request #131
Opened 2024-09-24 11:55 UTC by houssembaltii

2024-09-26 09:42 UTC, yoannfleurydev requested changes

2024-09-26 09:42 UTC, yoannfleurydev commented on src/content/meetup/2024-09-27-bangkok/about.tsx
> +              </Button>
Remove if href is empty

2024-09-26 09:42 UTC, yoannfleurydev commented on src/content/meetup/2024-09-27-bangkok/about.tsx
> +              alt=""
Need an alt on the image

2024-09-26 09:50 UTC, houssembaltii commented on src/content/meetup/2024-09-27-bangkok/about.tsx
> +              </Button>
i have asked rudy if we have info about where the meetup will be held , i ll update it when i get the info , if there is none i will delete

2024-09-30 08:16 UTC, JeanneGrenet commented on src/content/meetup/2024-09-27-bangkok/about.tsx
> +                      Come enjoy conferences and a networking cocktail .
cocktail.

2024-10-02 17:14 UTC, yoannfleurydev approved these changes

2024-10-02 17:14 UTC, merged