add partners section and react paris
Fork-It-Community/forkit.community pull request #14
Opened 2024-03-13 09:55 UTC by JeanneGrenet

## Description : 
Add a partner section in the homepage 

## Screen with 2 partners : 
I only put React Paris one time but it's for you to see with more partners
![image](https://github.com/Fork-It-Community/forkit.community/assets/77801791/bd0d1409-5260-41a9-8904-f21e390f231a)

2024-03-13 15:10 UTC, charlelisefouasse approved these changes

2024-03-15 10:11 UTC, yoannfleurydev requested changes

2024-03-15 10:11 UTC, yoannfleurydev commented on public/partners/react-paris.png
I think you didn't used the same template as the sponsors. We should to keep it homogeneous

2024-03-15 10:11 UTC, yoannfleurydev commented on src/app/(homepage)/page.tsx
>        {/* <Sponsors /> */}
We will remove the `<Sponsors />` comment by the way

2024-03-15 10:11 UTC, yoannfleurydev commented on src/app/(homepage)/partners.tsx
> +            Meet our partners
```suggestion
            Partners
```

2024-03-15 10:11 UTC, yoannfleurydev commented on src/app/(homepage)/partners.tsx
> +              <li key={partner.name} className="flex flex-col gap-4">
I'm not sure about the CSS here. There is only 1 element (the image).

2024-03-15 10:11 UTC, yoannfleurydev commented on src/app/(homepage)/partners.tsx
> +                    height={500}
After using the template on the image, you will have the good values for those.

2024-03-15 10:11 UTC, yoannfleurydev commented on src/app/(homepage)/partners.tsx
> +                  href={partner.href ?? "#"}
In the schema, URL is optional. We don't put the link if there is not href. `#` should not be in production.

2024-03-15 10:16 UTC, JeanneGrenet commented on src/app/(homepage)/partners.tsx
> +              <li key={partner.name} className="flex flex-col gap-4">
There will be other images with other partners no ?

2024-03-18 08:00 UTC, yoannfleurydev commented on src/app/(homepage)/partners.tsx
> +              <li key={partner.name} className="flex flex-col gap-4">
Yeah, but each partner is in an `li`. `flex flex-col` won't be useful for just an image.

2024-03-29 12:54 UTC, ivan-dalmet approved these changes

2024-03-29 12:55 UTC, merged