Feat/component conference card v2
Fork-It-Community/forkit.community pull request #144
Opened 2024-10-02 11:25 UTC by IounOm

## What does it do?
- split the Conference Card component into three component
  - Break Card
  - Conference Card
  - Event Program

Additional code from PR [#103](https://github.com/Fork-It-Community/forkit.community/pull/103) in branch  [feat/component-conference-card](https://github.com/Fork-It-Community/forkit.community/tree/feat/component-conference-card)
- add badge, location badge, language badge and favorite button from the existing one
- add conference/break card & program event card

## Screenshot
![Screenshot 2567-10-02 at 18 10 13](https://github.com/user-attachments/assets/5380e9c6-40ae-4ffe-8af8-b6a35eeabfa5)
![Screenshot 2567-10-02 at 18 10 36](https://github.com/user-attachments/assets/77c3020c-b905-4825-8614-add644ebfe5e)

## Related issue
- close #78

2024-10-02 13:42 UTC, JeanneGrenet requested changes

2024-10-02 13:42 UTC, JeanneGrenet commented on src/pages/branding/components/conference-card.astro
> +const events = await getEntry("events", "rouen-france-2024");
get entry returns one entry so here one event : `const event = await getEntry("events", "rouen-france-2024")`

2024-10-02 17:37 UTC, yoannfleurydev commented on src/pages/branding/components/conference-card.astro
> +const events = await getEntry("events", "rouen-france-2024");
I think we should inject fake data in those pages. They are used like a simple StoryBook for Astro.

2024-10-03 03:43 UTC, IounOm commented on src/components/event-program.tsx
> +};
My next solution is to create a 'type' folder to store type data, allowing it to be shared across other data sources.

I will inform you again once it’s fixed.

2024-10-03 03:44 UTC, IounOm commented on src/pages/branding/components/conference-card.astro
> +const events = await getEntry("events", "rouen-france-2024");
Alright, I have broken down the necessary fixes into three parts:

1. This component is part of the event section, so I will move the code to the event folder.
2. Since I'm currently using `GetEntry` and `GetCollection` to fetch data, I will relocate this code from the page to the lip folder and call it from there instead.
3. The current event data fetching is done using `getEntry("events", "rouen-france-2024")`, which retrieves only one event. I will modify it to fetch data using `GetCollection` to retrieve multiple events.

If there’s anything else that needs to be adjusted or improved, please let me know.

2024-10-03 03:54 UTC, IounOm commented on src/components/event-program.tsx
> +  startTime?: Date | undefined;
ok I will fix this.

I will inform you again once it’s fixed.

2024-10-03 07:32 UTC, IounOm commented on src/pages/branding/components/conference-card.astro
> +const events = await getEntry("events", "rouen-france-2024");
I am currently using the component from the file `/page/branding/components/conference-card.astro`, which doesn’t align with the other components being used.

I have broken down the necessary fixes into three parts:
1. Move the usage from `/page/branding/components/conference-card.astro` to `/content/component/conference-card.mdx` instead.
2. Use mock data instead of calling `getEntry` and `getCollection`.
3. Remove `useState` and `useEffect` in all components since React state cannot be used in `.mdx` files.

If there’s anything else that needs to be adjusted or fixed, please let me know.

2024-10-03 09:51 UTC, IounOm commented on src/components/event-program.tsx
> +};
fixed!

2024-10-03 09:53 UTC, IounOm commented on src/components/event-program.tsx
> +};
Fixed!

2024-10-03 09:53 UTC, IounOm commented on src/components/event-program.tsx
> +  startTime?: Date | undefined;
Fixed!

2024-10-03 09:53 UTC, IounOm commented on src/pages/branding/components/conference-card.astro
> +const events = await getEntry("events", "rouen-france-2024");
Fixed!

2024-10-03 10:05 UTC, IounOm commented
## Update Feature
Updated at 3 Oct 24
- Move type from component to export type in `.ts` file from content folder
- Edit the startTime type declaration from `TimeAndDuration` function in `src/components/event-program.tsx`
- Move the usage from `/page/branding/components/conference-card.astro` to `/content/component/conference-card.mdx `instead.
- Use mock data instead of calling `getEntry` and `getCollection`.
- Remove `useState` and `useEffect` in all components since React state cannot be used in `.mdx` files.

![image](https://github.com/user-attachments/assets/63152809-03a9-4cb9-9ab9-03a8390a2eac)
![image](https://github.com/user-attachments/assets/cc6ecc32-92ac-43cb-838f-4e2963b2f8bb)
![image](https://github.com/user-attachments/assets/0e90a55d-f4bf-4c1d-a78e-815caf5cd088)
![image](https://github.com/user-attachments/assets/a2f83ea6-c081-4d89-b8a3-23e420c7e662)

2024-10-04 08:12 UTC, houssembaltii requested changes

2024-10-04 08:12 UTC, houssembaltii commented on src/content/speakers/speaker.ts
> +export type SpeakerContent = {
When trying to use type of a collection , you can use `collectionEntry` from astro 
check [docs](https://docs.astro.build/en/reference/api-reference/#collection-entry-type) 
![image](https://github.com/user-attachments/assets/3013de6d-5129-482a-9cdd-5452afcb7adf)

2024-10-04 08:12 UTC, houssembaltii commented on src/content/sponsors/sponsors.ts
> +
Same :arrow_up:

2024-10-04 08:12 UTC, houssembaltii commented on src/content/talks/talks.ts
> +export type TalkContent = {
Same :arrow_up:

2024-10-08 08:57 UTC, IounOm commented on src/components/break-card.tsx
> +  }
fixed!

2024-10-08 08:57 UTC, IounOm commented on src/components/conference-card.tsx
> +  let talk = {} as Talk;
fixed!

2024-10-08 09:00 UTC, IounOm commented on src/content/speakers/speaker.ts
> +export type SpeakerContent = {
fixed!
(Currently, the content for speakers folder has been moved to use in people folder instead, so the type fetching has been updated accordingly.)

2024-10-08 09:00 UTC, IounOm commented on src/content/sponsors/sponsors.ts
> +
fixed!

2024-10-08 09:01 UTC, IounOm commented on src/content/talks/talks.ts
> +export type TalkContent = {
fixed!

2024-10-08 18:00 UTC, houssembaltii requested changes
We will use React components only for displaying content, not for tasks like searching for sponsors or talks.... I suggest modifying the props to pass only the data that needs to be displayed.

2024-10-15 08:21 UTC, JeanneGrenet requested changes

2024-10-15 08:21 UTC, JeanneGrenet commented on src/components/event-program.tsx
> +            <div className="flex flex-col gap-4">
Key props is missing for the map

2024-10-17 10:36 UTC, IounOm commented on src/components/break-card.tsx
> +          <p className="text-xl font-semibold">{props?.schedule?.name}</p>
fixed!

2024-10-17 10:36 UTC, IounOm commented on src/components/break-card.tsx
> +                alt={sponsor?.image?.alt}
fixed!

2024-10-17 10:36 UTC, IounOm commented on src/components/event-program.tsx
> +            <div className="flex flex-col gap-4">
fixed!

2024-12-19 10:38 UTC, houssembaltii commented
this is pull rquest is merged in this one https://github.com/Fork-It-Community/forkit.community/pull/170

2024-12-19 10:38 UTC, closed without merging