Feat: component faq v2
Fork-It-Community/forkit.community pull request #153
Opened 2024-10-08 11:01 UTC by IounOm

## What does it do?
- edit FAQ component from comment in PR #114

Additional code from PR [#114](https://github.com/Fork-It-Community/forkit.community/pull/114) in branch  [feat/component-faq](https://github.com/Fork-It-Community/forkit.community/tree/feat/component-faq)
- create FAQ component

## Screenshot
<img width="592" alt="Screenshot 2567-10-08 at 18 09 59" src="https://github.com/user-attachments/assets/806bb02e-d1fd-4a83-be26-f204c148d5b9">
<img width="789" alt="Screenshot 2567-10-08 at 17 57 15" src="https://github.com/user-attachments/assets/b51f7248-196b-45ac-9de5-2379104cfc5c">

## Related issue
- close #81

2024-10-08 16:27 UTC, houssembaltii requested changes
besides those two small comments , everything is ok to me !

2024-10-08 16:27 UTC, houssembaltii commented on src/components/faq.tsx
> +          {props.title}
it's called FAQ (Frequently Asked Questions)  component, i don't think we will use another title except Frequently Asked Questions .

2024-10-08 16:27 UTC, houssembaltii commented on src/components/faq.tsx
> +};
```suggestion
  faq: CollectionEntry<"events">["data"]["faq"];
};
```

2024-10-09 04:37 UTC, IounOm commented on src/components/faq.tsx
> +          {props.title}
fixed!

2024-10-09 04:37 UTC, IounOm commented on src/components/faq.tsx
> +};
Fixed!

2024-10-15 08:13 UTC, JeanneGrenet approved these changes

2024-10-15 08:37 UTC, houssembaltii approved these changes

2024-11-05 13:45 UTC, merged