Feat: component speaker v2
Fork-It-Community/forkit.community pull request #157
Opened 2024-10-09 11:26 UTC by IounOm

## What does it do?
- edit component speaker in PR #98 
- split component speaker to 2 component
  - SpeakerDetail -> for render single speaker
  - SpeakerGroup -> for render multiple speaker

## Screenshot
![Screenshot 2567-10-09 at 18 22 14](https://github.com/user-attachments/assets/8e85528e-3d7c-4b41-9d13-28eff9cfe53b)
![Screenshot 2567-10-09 at 18 23 01](https://github.com/user-attachments/assets/b456f48d-19cc-45e2-a1d4-434cf24bfdf0)

## Related issue
- close #79

2024-10-15 08:01 UTC, JeanneGrenet requested changes

2024-10-16 08:15 UTC, IounOm commented on src/components/speakerDetail.tsx
> +        <SpeakerDetail speaker={speaker.data} />
fixed!

2024-10-16 11:02 UTC, IounOm commented
Update 16 Oct 24
- add SpeakerCarousel component

![Screenshot 2567-10-16 at 18 01 40](https://github.com/user-attachments/assets/68c6102a-6d91-489b-8210-7bad62d1595b)
![Screenshot 2567-10-16 at 18 02 00](https://github.com/user-attachments/assets/97196730-71f0-4f13-af4c-df9703af6904)

2024-10-16 11:07 UTC, IounOm commented
Update 16 Oct 24
- add SpeakerCarousel component

![Screenshot 2567-10-16 at 18 07 10](https://github.com/user-attachments/assets/4bfaefa7-ff7b-4ae3-9c6a-0580d2973c6d)
![Screenshot 2567-10-16 at 18 05 50](https://github.com/user-attachments/assets/561650aa-0d70-4c71-99ff-9a2ccdb70833)

2024-10-17 08:49 UTC, JeanneGrenet approved these changes

2024-10-17 15:25 UTC, houssembaltii commented on src/components/speakerDetail.tsx
> +const SpeakerGroup = (
```suggestion
const Speakers = (
```

2024-10-17 15:25 UTC, houssembaltii approved these changes

2024-10-22 04:47 UTC, IounOm commented on src/components/speakerDetail.tsx
> +const SpeakerGroup = (
fixed!

2024-11-05 13:44 UTC, merged