Feat: component event card v2
Fork-It-Community/forkit.community pull request #158
Opened 2024-10-09 14:39 UTC by IounOm

## What does it do?
- edit component event card in PR #97 

## Screenshot
![Screenshot 2567-10-09 at 21 38 42](https://github.com/user-attachments/assets/e8be5d60-95f9-4fbd-9b40-6259536ffd12)
![Screenshot 2567-10-09 at 21 39 21](https://github.com/user-attachments/assets/22953aaf-cf8c-4ba9-a319-703e09f9181f)

## Related issue
- close #73

2024-10-15 07:48 UTC, JeanneGrenet requested changes

2024-10-15 07:48 UTC, JeanneGrenet commented on src/components/event-card.tsx
> +  const eventType = "cfp" in props.event ? "event" : "meetup";
We can have cfp for meetups too. I think we should add a props to specify if it's an event or a meetup

2024-10-15 07:48 UTC, JeanneGrenet commented on src/components/event-card.tsx
> +                {"cfp" in props.event && props.event.cfp?.endDate && (
props.event.cfp && props.event.cfp?.endDate && (

2024-10-15 07:48 UTC, JeanneGrenet commented on src/components/event-card.tsx
> +      {eventType === "event" && (
I think we can have a `cont isEvent = eventType === "event"` at the beginging and use it for the checks to avoid multiple comparison

2024-10-16 08:47 UTC, IounOm commented on src/components/event-card.tsx
> +  const eventType = "cfp" in props.event ? "event" : "meetup";
fixed!

2024-10-16 08:47 UTC, IounOm commented on src/components/event-card.tsx
> +                {"cfp" in props.event && props.event.cfp?.endDate && (
fixed!

2024-10-16 08:47 UTC, IounOm commented on src/components/event-card.tsx
> +      {eventType === "event" && (
fixed!

2024-10-17 08:31 UTC, JeanneGrenet approved these changes

2024-10-17 15:21 UTC, houssembaltii requested changes
I think it will be better if we seperate this component into two : 
* `EventCard`
* `MeetupCard` 

Make sure you  keep them in the same file  rename  it

2024-10-22 10:18 UTC, IounOm commented on src/components/event-card.tsx
> +                  </time>
successfully implemented!

2024-10-22 10:18 UTC, IounOm commented
> I think it will be better if we seperate this component into two :
> 
> * `EventCard`
> * `MeetupCard`
> 
> Make sure you keep them in the same file rename it

successfully implemented!

2024-10-22 10:23 UTC, IounOm commented
update 22 Oct 24
- Split the component into two parts: `EventCard` and `MeetupCard`.
- Rename the file to `activity-card.tsx` to align with both components.

![Screenshot 2567-10-22 at 17 19 19](https://github.com/user-attachments/assets/a08a972d-77f5-4267-b544-0b8a603ba9a5)
![Screenshot 2567-10-22 at 17 19 31](https://github.com/user-attachments/assets/4bdd8345-314f-4c0e-8934-1024ce69fef6)

2024-10-22 15:11 UTC, houssembaltii commented on src/components/activity-card.tsx
> +
the `EventCard` is for an event and `MeetupCard` is for a meetup , so there is no need for the props type to be `Event | Meetup`

2024-10-28 07:26 UTC, IounOm commented on src/components/activity-card.tsx
> +
fixed!

2024-11-05 10:29 UTC, houssembaltii approved these changes

2024-11-05 13:42 UTC, merged