Add speaker componenet
Fork-It-Community/forkit.community pull request #16
Opened 2024-03-15 09:36 UTC by JeanneGrenet

## Description
We want to display the information about the speakers on the event page. When there is no speaker for an event the component is not display

## Screenshot : 
![image](https://github.com/Fork-It-Community/forkit.community/assets/77801791/fe45aa54-97f4-47ff-a64f-574310b2c159)

2024-03-15 10:37 UTC, charlelisefouasse requested changes

2024-03-15 10:37 UTC, charlelisefouasse commented on src/app/events/[slug]/speaker.tsx
> +}
Je sais pas les regles pour ce projet mais en general je prefere que ce soit extrait dans un fichier a part et avoir qu'un composant par fichier

2024-03-15 10:37 UTC, charlelisefouasse commented on src/app/events/[slug]/speaker.tsx
> +const icons = {
on a pas un endroit où on met les icons ? elles sont pas utilisables ailleurs ?

2024-03-15 10:37 UTC, charlelisefouasse commented on src/content/collections.ts
> +            type: z.enum(["x", "linkedin", "instagram"]),
par exemple sur react paris les speakers ont leur github de link je pense que c'est interessant de l'ajouter

2024-03-15 10:37 UTC, charlelisefouasse commented on src/app/events/[slug]/speaker.tsx
> +          {!!props.event.speakers &&
je sais pas c'est quoi la regle sur ce projet pour "!!" mais la dans ton code des fois tu le met des fois tu le met pas, faut choisir :P

2024-03-15 10:37 UTC, charlelisefouasse commented on src/app/events/[slug]/speaker.tsx
> +      <p className="text-sm leading-6 text-gray-400">{speaker.job}</p>
je trouve que sur ton screen ca manque de visibilité,  voir si faut changer la couleur, la taille ou le gras idk

2024-03-15 10:37 UTC, charlelisefouasse commented on src/app/events/[slug]/page.tsx
> +import { Speakers } from "./speaker";
```suggestion
import { Speakers } from "./speakers";
```

2024-03-15 10:40 UTC, charlelisefouasse commented on src/app/events/[slug]/speaker.tsx
> +      <p className="text-sm leading-6 text-gray-400">{speaker.job}</p>
quand j'y repense je trouve que le nom et le job sont vraiment trop petits 

exemple react paris 

![image](https://github.com/Fork-It-Community/forkit.community/assets/107464660/640aa073-fa27-46f1-8384-93171ec7e8b5)

2024-03-15 15:55 UTC, JeanneGrenet commented on src/app/events/[slug]/speaker.tsx
> +}
Pour les sponsors on a tout mis dans le même fichier donc j'ai fait pareil

2024-03-15 16:04 UTC, JeanneGrenet commented on src/app/events/[slug]/speaker.tsx
> +const icons = {
Je ne sais pas trop, celles du footer sont directement dans le fichier footer

2024-04-10 11:45 UTC, yoannfleurydev approved these changes

2024-04-10 11:46 UTC, merged