feat: create component map location
Fork-It-Community/forkit.community pull request #164
Opened 2024-10-17 09:49 UTC by IounOm

## What does it do?
- feat: create component map location

## Screenshot
![Screenshot 2567-10-17 at 16 48 15](https://github.com/user-attachments/assets/37c0064d-1bdc-4173-99d8-a5f28cd423e0)
![Screenshot 2567-10-17 at 16 47 45](https://github.com/user-attachments/assets/8e54d741-9bd0-4321-903d-1436ddcd8f22)

## Related issue
-

2024-10-17 13:14 UTC, JeanneGrenet requested changes

2024-10-17 13:14 UTC, JeanneGrenet commented on src/components/map-location.tsx
> +    eventsSubPages: EventsSubPages;
This component will also be used in meetup "home" page. I think we should have `title` and `address` but not in the event subpages

2024-10-22 10:34 UTC, IounOm commented on src/components/map-location.tsx
> +          </p>
I noticed that the map on the meetup page doesn't have a pin icon, so I didn't include it.
The next steps are:
- Add the pin icon.
- Create props to show/hide the icon for reuse on other pages.

![Screenshot 2567-10-22 at 17 30 34](https://github.com/user-attachments/assets/aefcf060-6e71-48c7-8078-9f83c20f7526)

2024-10-22 10:54 UTC, IounOm commented on src/components/map-location.tsx
> +    eventsSubPages: EventsSubPages;
fixed!

2024-10-22 10:54 UTC, IounOm commented on src/components/map-location.tsx
> +          </p>
fixed!

2024-10-22 14:53 UTC, IounOm commented on src/components/map-location.tsx
> +          </p>
fixed!

2024-10-28 08:43 UTC, JeanneGrenet requested changes

2024-10-28 08:43 UTC, JeanneGrenet commented on src/components/map-location.tsx
> +        {!hideIcon && <div className="pt-2">{ICONS.pin}</div>}
We should use que `<MapPin /> `icon from lucid react to have the same icons everywhere

2024-10-28 08:43 UTC, JeanneGrenet commented on src/content/components/map-location.mdx
> +    hidePinIcon
What is this props for ?

2024-10-29 05:41 UTC, IounOm commented on src/content/components/map-location.mdx
> +    hidePinIcon
I see in meetup page that not have pin icon on it so I write this use for reuse between 2 page form design form this capture image. Component will show pin icon by default but can remove it by add props `hidePinIcon`

if pin icon always needs to be included. I'll remove this prop and set the icon as a fixed value instead.

![Screenshot 2567-10-29 at 12 27 39](https://github.com/user-attachments/assets/382b4b77-c981-4b6b-a06b-7e6ce28eb93f)
![Screenshot 2567-10-29 at 12 28 33](https://github.com/user-attachments/assets/ab40ceb4-5e97-47c4-a875-5d3bf5e7a258)

2024-10-29 07:32 UTC, IounOm commented on src/content/components/map-location.mdx
> +    hidePinIcon
fixed!

2024-10-29 07:32 UTC, IounOm commented on src/components/map-location.tsx
> +        {!hideIcon && <div className="pt-2">{ICONS.pin}</div>}
fixed!

2024-11-05 10:44 UTC, houssembaltii approved these changes

2024-11-06 09:38 UTC, JeanneGrenet approved these changes

2024-11-06 09:39 UTC, merged