Feat: create component explore the community
Fork-It-Community/forkit.community pull request #96
Opened 2024-08-28 07:44 UTC by build-ratchanon

## What does it do?

- create "explore the community" component 

## Screenshot
![image](https://github.com/user-attachments/assets/9da27e65-2037-4469-80ca-ae59c2fedbc2)

2024-08-28 09:06 UTC, yoannfleurydev requested changes

2024-08-28 09:06 UTC, yoannfleurydev commented on yarn.lock
Please use https://pnpm.io/

2024-08-28 16:27 UTC, yoannfleurydev requested changes

2024-08-28 16:27 UTC, yoannfleurydev commented on src/components/explore-the-community.tsx
> +import { Button } from "./ui/button";
Please use absolute imports.

```suggestion
import { Button } from "@/components/ui/button";
```

2024-08-28 16:27 UTC, yoannfleurydev commented on src/components/explore-the-community.tsx
> +      </Button>
The button should take optionnal props so we can give it a link (default to `/`)

2024-08-28 16:27 UTC, yoannfleurydev commented on src/components/explore-the-community.tsx
> +      </p>
I think the `title` props should be optionnal and default to `Fork it! Community`.

2024-08-28 16:27 UTC, yoannfleurydev commented on src/components/explore-the-community.tsx
Please use Prettier to format the code.

All the config is in the repo, you need to configure your IDE.

2024-08-28 16:27 UTC, yoannfleurydev commented
Also, is it possible to link the issue to the PR please, so we can keep track of which PR goes with which issue.

Thanks.

2024-09-04 08:07 UTC, JeanneGrenet requested changes

2024-09-04 08:07 UTC, JeanneGrenet commented on src/components/explore-the-community.tsx
> +      <Button asChild size="sm" className="max-h-6 text-xs">
On the mockups the padding is `8px `but here the padding is `12px`

2024-09-05 08:41 UTC, JeanneGrenet approved these changes

2024-09-17 08:22 UTC, houssembaltii commented on src/components/explore-the-community.tsx
> +    <div className="flex min-h-10 flex-row items-center justify-between gap-1 rounded-md bg-neutral-900 bg-opacity-40 p-2 pl-4">
```suggestion
    <div className="flex min-h-10 flex-row items-center justify-between gap-1 rounded-lg bg-neutral-900 bg-opacity-40 p-2 pl-4">
```

2024-09-17 08:23 UTC, houssembaltii commented on src/components/explore-the-community.tsx
> +    <div className="flex min-h-10 flex-row items-center justify-between gap-1 rounded-md bg-neutral-900 bg-opacity-40 p-2 pl-4">
according to the [figma design ](https://www.figma.com/design/qt0YXmmXYz0sMx6SYTh84X/branch/4CuDzedIt5n3dLji9FR25d/Digital-Platform?node-id=3462-3410&node-type=frame&m=dev)the border radius is 8 px   .

2024-09-18 07:06 UTC, yoannfleurydev approved these changes

2024-09-18 07:06 UTC, merged