Feat: component event card
Fork-It-Community/forkit.community pull request #97
Opened 2024-08-28 07:54 UTC by build-ratchanon

## What do I do?
- create event card in difference type. conference and meetup

## Screenshot
- conference
![image](https://github.com/user-attachments/assets/d898c67f-9cf2-48cb-a769-179a027b4481)
- meetup
![image](https://github.com/user-attachments/assets/d7a596f9-e8ae-4c9b-82a9-78f09d7f6543)

2024-08-29 07:45 UTC, yoannfleurydev requested changes

2024-08-29 07:45 UTC, yoannfleurydev commented on src/components/event-card.tsx
> +        ${props.eventType === 'conference' ? 'bg-cover bg-center' : ''}
Something is wrong, you got the same condition here

2024-08-29 07:45 UTC, yoannfleurydev commented on src/components/event-card.tsx
> +        ${props.eventType === 'conference' ? 'bg-cover bg-center' : ''}
Also, there is a utility `cn` provided by `shadcn ui` to do condition classes (it is a mix based on `clsx` and `tailwind-merge`) in utils.

2024-08-29 07:45 UTC, yoannfleurydev commented on src/components/event-card.tsx
> +        ></div>
```suggestion
        />
```

2024-09-04 09:01 UTC, JeanneGrenet requested changes

2024-09-17 09:41 UTC, houssembaltii commented on src/components/event-card.tsx
> +export const EventCard = (props: EventCardProps) => {
i agree with @JeanneGrenet

2024-09-17 13:06 UTC, houssembaltii commented on src/components/event-card.tsx
> +            </div>
Using `<div>` all the time is bad practice . Whenever an appropriate semantic tag is available, we should use it instead.
 for example : instead of using `<div>` here you can use 
```suggestion
            <p className="flex flex-col font-heading text-base text-secondary">
              {props.title}
            </p>
```

2024-10-09 14:53 UTC, closed without merging

2024-10-16 15:01 UTC, houssembaltii commented
This pull request will be replace by #158